application: lifeshow-kuber
version: 6
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "4d"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /touch\-icon\-(.*)\.png
  static_files: static/touch-icon-\1.png
  upload: static/touch\-icon\-(.*)\.png

- url: /static
  static_dir: static

- url: /resume/(.+)
  static_files: resume/\1
  upload: resume/(.*)\.(png|css|jpeg|jpg|ico|js|gif)

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?\.bak
