runtime: python27
api_version: 1
threadsafe: true
default_expiration: "4d"

handlers:
- url: /.*
  script: main.app

includes:
- static/static.yaml
- resume/resume.yaml

libraries:
- name: webapp2
  version: latest

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?\.bak
